idea.config.path=${user.dir}/.tooling/studio-config
idea.system.path=${user.dir}/.tooling/studio-system
idea.plugins.path=${user.dir}/.tooling/studio-plugins
idea.log.path=${user.dir}/.tooling/studio-logs
