plugins { id 'com.android.application' }

android {
    namespace 'fr.fonote'
    compileSdk 35
    defaultConfig {
        applicationId 'fr.fonote'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0.0'
        testInstrumentationRunner 'fr.fonote.OfflineChecks'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
